### ISSUE TITLE
biuld_stubbed hits the database

### ISSUE THREAD

**Issue by retgoat** [thoughtbot/factory_girl_rails#138]
Hi All.
I have rails 4 application with two databases.
One database is a one I can't affect on.
So, in tests I'd like to stub model creation with 

```ruby
FactoryGirl.build_stubbed(:factory)
```

But I'm getting this error:
```
 Failure/Error: account = FactoryGirl.build_stubbed(:abp_account)
     ActiveRecord::StatementInvalid:
       Mysql2::Error: Table 'ABPPROD.ACCOUNTS' doesn't exist: SHOW FULL FIELDS FROM `ABPPROD`.`ACCOUNTS`
     # ./spec/models/abp/account_spec.rb:7:in `block (3 levels) in <top (required)>'
```

Here is my factory
```ruby
FactoryGirl.define do
  factory :abp_account, :class => "Abp::Account" do
    accountnumber 12095
    originid 10
    username 'elecs1'
    email 'test@example.com'
    ipaddress '1.1.1.1'
    countryid 74
  end
end
```

Here is my test
```ruby
require 'rails_helper'

RSpec.describe Abp::Account, :type => :model do

  describe '#accountnumber' do
    it 'returns accountnumber' do
      account = FactoryGirl.build_stubbed(:abp_account)
      expect(account.accountnumber).to eq(12345)
    end # it
  end # describe accountnumber
end #RSpec describe
```

Here is model
```ruby
class Abp::Account < ActiveRecord::Base
  establish_connection :abp
  self.table_name = 'ABPPROD.ACCOUNTS'
end
```

Moreover, when I try to build model in test console it works. But it doesen't in tests.
```
2.1.2 :002 > Rails.env
 => "test"

2.1.2 :010 > ac = FactoryGirl.build_stubbed(:abp_account)
=> #<Abp::Account id: 1001, written: ...

2.1.2 :010 > ac.class.name
=> "Abp::Account" 

2.1.2 :011 > ac.inspect
 => "#<Abp::Account id: 1001, written: ...
```
I'd like to just stub new model creation. Is this possible?
Thanks!

**Comment by joshuaclayton** [comment]
@retgoat I think what's happening is that even though Factory Girl doesn't actually interact with the database, the Rails app itself is loading the model and looking for the table (which doesn't exist).

I believe you'd be able to verify this by running `RAILS_ENV=test rails console` and then `Abp::Account.new` from within the console itself.

I'm going to close this, but feel free to reopen if you're still running into this issue.
