### ISSUE TITLE
Non-association attributes ignore passed in values on `FactoryGirl::create`

### ISSUE THREAD

**Issue by brittlewis12** [thoughtbot/factory_girl_rails#139]
I'm working with an object that has both `service_type` and `service_type_id` attributes (no association at all, it's from a third party system), and the Factory nils out the non-id attribute each time I try to set both by passing a hash to `.create`:
```ruby
FactoryGirl.create(:service, service_type: 'help', service_type_id: 105)
# => #<Service id: 1, service_type: nil, service_type_id: 105>
```

When both attributes are defined inside a `FactoryGirl.define` block, when **no hash** is passed in to `.create`, the factory object has both attributes:
```ruby
FactoryGirl.define do
  factory :service do
    service_type { 'default service' }
    service_type_id { 10 }
  end
end

FactoryGirl.create(:service)
# => #<Service id: 1, service_type: 'default service', service_type_id: 10>
```

However, even with both defined in the Factory, attempting to override both values with a hash results in the same behavior as described above.

So far, the only work around is to assign the non-id attribute a value in an after block. This works, but of course I'd like to be able to assign values in the hash passed to `.create`. Does FactoryGirl assume attributes that differ only by '_id' at the end are meant to both reference an association? Might it be more desirable to require explicitly calling out an association as such to achieve this behavior?

(Using factory_girl_rails v4.2.1 and Rails 4.0)

**Comment by dabrorius** [comment]
This is probably related to FactoryGirl aliases, check out issue #109 it seems to be the same thing.

**Comment by brittlewis12** [comment]
Thanks for the link @dabrorius , it does indeed look the same.
