### ISSUE TITLE
FactoryGirl ignores my spec/factories.rb file

### ISSUE THREAD

**Issue by dwayne** [thoughtbot/factory_girl_rails#140]
If I create a new Rails app, set up `factory_girl_rails` and create `spec/factories.rb` to store my factories then FactoryGirl ignores it.

For example,

```sh
$ bin/rails g model User name
```

will generate a factory for users at `spec/factories/users.rb` when I want it to prepend/append the factory to my `spec/factories.rb` file.

**Comment by marceloboeira** [comment]
@dwayne this is not wise, at some point the factories file will be huge.

**Comment by dwayne** [comment]
@marceloboeira I think at the time it was a small project I was working on and I just wanted to have the factories in one file. But I agree with you, on a larger project there can be a lot of factories.

**Comment by marceloboeira** [comment]
@dwayne I'm not on the contributors team. @joshuaclayton can you close it?
