### ISSUE TITLE
Better support for UUID foreign keys

### ISSUE THREAD

**Issue by anthonator** [thoughtbot/factory_girl_rails#142]
About every other time I run a test I'm running into issues with my UUID foreign keys when testing uniqueness.

When a UUID of ```f9303ea7-5b55-4318-b88d-6eb63f33cc0f``` is naturally generated it gets converted to ```f9303ea7-5b55-4318-b88d-6eb63f33cc0g``` which is invalid (notice ending ```f``` changing to ```g```).

Also, when ```build_stubbed``` the keys aren't generated as UUID which also creates hassle.

**Comment by joshuaclayton** [comment]
@anthonator I'm going to close the issue in this repo; there's a related issue in the factory_girl repo that covers exactly this: https://github.com/thoughtbot/factory_girl/issues/713
