### ISSUE TITLE
Generator puts factory on same line with define statement

### ISSUE THREAD

**Issue by hahcho** [thoughtbot/factory_girl_rails#150]
When using the models generator i have the following issue:
My `factories.rb` before `rails g model Test value:string`:

    FactoryGirl.define do  
      # factory definitions
    end

After:

    FactoryGirl.define do factory :test, class => 'Test' do
        value "MyString"
      end  
      # factory definitions
    end

Probably a better idea is to write the factory definition after `FactoryGirl.define do`.

Setup:
`rails 3.2.19`, `factory_girl_rails 4.5.0`

**Comment by gabebw** [comment]
This still happens with more recent version of FG rails. I believe [this line](https://github.com/thoughtbot/factory_girl_rails/blob/master/lib/generators/factory_girl/model/model_generator.rb#L39) is the problem - it should probably insert after `""FactoryGirl.define do\n"` (note the newline).

**Comment by chrisccerami** [comment]
I'm still seeing this behavior when generating a model in Rails 4.2.1
