### ISSUE TITLE
'cannot load such file -- factory_girl_rails (LoadError)' in rails 4.1.8

### ISSUE THREAD

**Issue by radhikabhatt** [thoughtbot/factory_girl_rails#167]
While running rspec, I am getting the following error:

/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- factory_girl_rails (LoadError)
    from /Users/radhikabhatt/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
    from /Users/radhikabhatt/Desktop/work/cl_portalmiudla/spec/spec_helper.rb:19:in `<top (required)>'
    from /Users/radhikabhatt/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
    from /Users/radhikabhatt/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'

My gemfile.lock looks like:

factory_girl (4.5.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.5.0)
      factory_girl (~> 4.5.0)

spec_helper.rb has the line `require 'factory_girl_rails'`. Please let me know if I missed something here.

**Comment by joshuaclayton** [comment]
@radhikabhatt I'd verify you're in the environment you expect and that it's declared in the gemfile for that environment. Additionally, you shouldn't have to `require 'factory_girl_rails'` when using Bundler unless you explicitly set `require: false` in your Gemfile.

Let me know if this helps!

**Comment by pedrohenriquerls** [comment]
add ```require 'factory_girl_rails'``` works to me
