### ISSUE TITLE
Validation problems when creating a factory. Rails 4.2

### ISSUE THREAD

**Issue by laertispappas** [thoughtbot/factory_girl_rails#170]
Can not create a factory due to validation errors

Stack: 
(FactoryGirl::InvalidFactoryError)
- poll_option - Validation failed: Title can't be blank (ActiveRecord::RecordInvalid)
  from /home/lapis/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/linter.rb:4:in `lint!'
  from /home/lapis/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl.rb:59:in`lint'
  from /home/lapis/Dropbox/projects_final/pappas/spec/support/factorygirl.rb:8:in `block (2 levels) in <top (required)>'
  from /home/lapis/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:378:in`instance_exec'
  from /home/lapis/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:378:in `instance_exec'
  from /home/lapis/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:357:in`run'
  from /home/lapis/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1660:in `block in run_hooks_with'
  from /home/lapis/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1660:in`each'
  from /home/lapis/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1660:in `run_hooks_with'
  from /home/lapis/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1626:in`with_suite_hooks'
  from /home/lapis/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:114:in `block in run_specs'
  from /home/lapis/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:77:in`report'
  from /home/lapis/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:113:in `run_specs'
  from /home/lapis/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:89:in`run'
  from /home/lapis/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
  from /home/lapis/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in`invoke'
  from /home/lapis/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/exe/rspec:4:in `<top (required)>'
  from /home/lapis/.rbenv/versions/2.2.1/bin/rspec:23:in`load'
  from /home/lapis/.rbenv/versions/2.2.1/bin/rspec:23:in `<main>'

Factory: 

FactoryGirl.define do
  factory :poll_option do
    title 'Yes'
  end
end

My only validation in my model is this:
  validates_presence_of :title

**Comment by joshuaclayton** [comment]
@laertispappas oftentimes I've found this is due to code outside FG - specifically, either callbacks or observers for that particular model. If you instantiate a `PollOption` directly, assign title, and attempt to `save!`, do you see the same exception?

**Comment by laertispappas** [comment]
FactoryGirl.lint is validating all mu suite for valid factories. I had an invalid factory somewhere else in my code thus it's my mistake. Sorry for the inconvenience caused.

Thanks
