### ISSUE TITLE
Is there an easy way to remove factory girl references from my rails app?

### ISSUE THREAD

**Issue by vzelenko** [thoughtbot/factory_girl_rails#172]
I have an application that does not have the gem configured correctly, and I wanted to completely pull it out before trying to add it again.  Is there an easy way to do that?

I am not only talking about removing the gem from the system, but also any references to elswhere configured or generated components.

**Comment by joshuaclayton** [comment]
@vzelenko you'll want to remove any factory definition files (often found in `(spec|test)/factories(.rb|/*)`), as well as any file(s) you've used to configure FactoryGirl itself (dependent on your test framework and naming conventions - I put any FG config in `spec/support/factory_girl.rb`. Often, just searching your repo for the `FactoryGirl` constant gets most of the cases. If you're using the FG syntax methods (`attributes_for`, `build`, `build_stubbed`, `create`, and the permutations `*_pair`, and `*_list`, you'll want to remove those from your test suite as well.
