### ISSUE TITLE
Fields named :message raises "undefined method `printf='"

### ISSUE THREAD

**Issue by BananaNeil** [thoughtbot/factory_girl_rails#175]
In Ruby 2.1.1, Rails 4.1.1, and FactoryGirl 4.5.0, my model has an attribute titled `message`. When I try to set a value for the message filed via factory girl,

```
FactoryGirl.define do
  factory :model_name do
    message "This is a message"
  end
end
```

 it constantly raises an exception claiming `undefined method 'printf=' for #<ModelName:0x007feeff5c1048>`

I tracked the logic down to `FactoryGirl::Syntax::Default::DSL#factory`, where my factory definition block is passed to `FactoryGirl::DefinitionProxy.new#instance_eval` (lib/factory_girl/syntax/default.rb:14)

It seems that during rails environment compilation (not in the environment it's self), ruby 2.1.1's `MakeMakeFile` module (~/.rbenv/versions/2.1.1/lib/ruby/2.1.0/mkmf.rb) is included, which defines a method as:

```
  def message(*s)
    unless Logging.quiet and not $VERBOSE
      printf(*s)
      $stdout.flush
    end
  end
```

Because FactoryGirl instance evaluates my definition block, instead of calling method_missing for `message`, it runs through that mkmf.rb method, which attempts to call printf on the proxy instance. Because the proxy instance doesn't have a method called print f, it then calls method missing (in lib/factory_girl/definition_proxy.rb) and adds `printf` to the attribute list in place of `message`.

Then, when creating an instance of my model, factory girl makes an attempt to call `printf=` on my model instance, raising this error.

My assumption is there will be a similar problem with any of the methods in the `MakeMakeFile`.

There is one hackey solution to this problem, which is define a method `FactoryGirl::DefinitionProxy#message` which just calls `add_attribute(message, value, &block)`

.. But my intuition tells me that there is truely a fundamental flaw in how factory girl define methods via method missing. Anyway, I'm happy to submit a pull request, but I figured this is something that should be discussed as a community.

**Comment by joshuaclayton** [comment]
@BananaNeil there've been times where attribute names have collided with underlying objects in the system, and yes, this does come up when using `method_missing` occasionally. Your intuition about `add_attribute` is actually spot-on; instead of defining `FactoryGirl::DefinitionProxy#message`, though, you can just call `add_attribute` in your factory definition block:

```ruby
factory :model_name do
  add_attribute :message, "value"
  # or
  add_attribute(:message) { "XXX" * 15 }
end
```
