### ISSUE TITLE
Validation failed:  (ActiveRecord::RecordInvalid) with no error message

### ISSUE THREAD

**Issue by baileyspace** [thoughtbot/factory_girl_rails#182]
I recently upgraded my rspec to use rail_helper. Now when I'm running my tests all tests containing FactoryGirl fail. Running lint reveals that all factories are invalid with the following error message: `Validation failed:  (ActiveRecord::RecordInvalid)`. No validation error message is available.

**Comment by joshuaclayton** [comment]
@baileyspace if you attempt to create records from within console (without FactoryGirl), do you see the same failures? Most often, this is a problem with the underlying models, take a look at https://github.com/thoughtbot/factory_girl/wiki/How-factory_girl-interacts-with-ActiveRecord as a reference and let me know how debugging goes.

**Comment by baileyspace** [comment]
I got it up and running again. I had changed a before_validation declaration to assign false to an attribute, and that threw a wrench in the gears. More on that here http://stackoverflow.com/questions/9007093/rails-getting-validation-failed-error-but-no-errors-in-activerecord-error-model

**Comment by joshuaclayton** [comment]
@baileyspace great news, thanks for following up! I'll close this.

**Comment by olivierlacan** [comment]
Fixed link for reference since the rename broke @joshuaclayton's link above: https://github.com/thoughtbot/factory_bot/wiki/How-factory_bot-interacts-with-ActiveRecord
