### ISSUE TITLE
Devise model incorrect instantiation

### ISSUE THREAD

**Issue by khataev** [thoughtbot/factory_girl_rails#187]
Seems to me, there is a bug, incorrect object instantiation of model User by Factory Girl in RSpec tests. I'm not sure which of them is guilty, description is on [StackOverflow](http://stackoverflow.com/questions/35133825/factory-girl-associated-object-instantiation-using-devise)

**Comment by jferris** [comment]
I don't believe this is a bug in FactoryGirl. I responded to your question on StackOverflow.
