### ISSUE TITLE
News file entry missing for v4.5.0 and v4.6.0

### ISSUE THREAD

**Issue by betelgeuse** [thoughtbot/factory_girl_rails#188]
https://github.com/thoughtbot/factory_girl_rails/blob/v4.6.0/NEWS

The latest entry is for 4.4.1

**Comment by joshuaclayton** [comment]
@betelgeuse I just released [4.7.0](https://github.com/thoughtbot/factory_girl_rails/releases/tag/v4.7.0) with notes on changes from 4.6 to 4.7 - interested in opening a PR outlining changes to 4.5?
