### ISSUE TITLE
Database column not visible through tests, even though it's verified to be present in the db

### ISSUE THREAD

**Issue by stabenfeldt** [thoughtbot/factory_girl_rails#189]
spree_users.deleted_at is present from `RAILS_ENV=test rails console`, but not inside a test.
Failing test:
```
    $ rspec ./spec/models/spree/permission_sets/restricted_stock_transfer_display_spec.rb:40

      1) Spree::PermissionSets::RestrictedStockTransferDisplay when not activated
         Failure/Error: let(:user) { create :user }
         ActiveRecord::StatementInvalid:
           PG::UndefinedColumn: ERROR:  column spree_users.deleted_at does not exist
           LINE 1: ..."spree_users"."email" = 'darby@tremblay.name' AND "spree_use...
                                                                        ^
           : SELECT  1 AS one FROM "spree_users" WHERE ("spree_users"."email" = 'darby@tremblay.name' AND "spree_users"."deleted_at" IS NULL) LIMIT 1

```
**user_factory.rb**

    require 'spree/testing_support/sequences'
    require 'spree/testing_support/factories/role_factory'
    require 'spree/testing_support/factories/address_factory'

    FactoryGirl.define do
    
      factory :user, class: Spree.user_class do
        email { generate(:random_email) }
        login { email }
        password 'secret'
        password_confirmation { password }
        authentication_token { generate(:user_authentication_token) } if Spree.user_class.attribute_method? :authentication_token
       
         # [cut...]    

      end
    end

**deleted_at is present in the database**

    $ psql Solidus_test
    psql (9.4.5)
    
    Solidus_test=# \d spree_users

    Table "public.spree_users"
                 Column         |            Type             |                        Modifiers
        ------------------------+-----------------------------+----------------------------------------------------------
        
         deleted_at             | timestamp without time zone |

**And I am connecting to Solidus_test:**

    $ grep 'test'  config/database.yml -A2
    test:
      <<: *default
      database: Solidus_test

**But not present in Spree::User.column_names**

If I throw in a `byebug` in the test before `create(:user)` I discover this:

    (byebug) Spree::User.column_names

    ["id", "encrypted_password", .....]

^  No "deleted_at"

Checking the test environment outside the rspec loop reveals that `deleted_at` is present:

```
✗ RAILS_ENV=test r c
Running via Spring preloader in process 4092
Loading test environment (Rails 4.2.5)
irb: warn: can't alias context from irb_context.
2.2.3 :001 > Spree::User.column_names
 => ["id", "encrypted_password", "password_salt", "email", "remember_token", "persistence_token", 
"reset_password_token", "perishable_token", "sign_in_count", "failed_attempts", "last_request_at", 
"current_sign_in_at", "last_sign_in_at", "current_sign_in_ip", "last_sign_in_ip", "login", 
"ship_address_id", "bill_address_id", "authentication_token", "unlock_token", "locked_at", 
"reset_password_sent_at", "created_at", "updated_at", "spree_api_key", "remember_created_at", 
"deleted_at", "confirmation_token", "confirmed_at", "confirmation_sent_at"]


```
Any tips why this is happening? Can I provide you any more debug info?

Cheers,
Martin

**Comment by joshuaclayton** [comment]
@stabenfeldt based on this, it looks like there's an issue with RSpec's interaction with `Spree::User` and not with FactoryGirl; I'd look through your RSpec configuration to see what might be interacting with the list of columns to narrow it down. To help rule out FactoryGirl, could you run a quick test to verify it's an issue with the model, by doing something like:

```ruby
# spec/models/spree_user_spec.rb

require "rails_helper"

RSpec.describe "Spree user" do
  it "works without FactoryGirl" do
    expect {
      Spree::User.new(deleted_at: Time.current)
    }.not_to raise_error
  end
end
```

With that in place, you should be able to go through your spec/rails helper files to identify what's breaking this behavior.

**Comment by stabenfeldt** [comment]
Thanks for the tips @joshuaclayton! :dancer: 
Having an other look at my spec_helper revealed a cut´n paste error:
`require File.expand_path("../dummy/config/environment", __FILE__)`
Should have been:
`require File.expand_path("../../config/environment", __FILE__)`

The test you provided went green when I fixed that. :-)

**Comment by joshuaclayton** [comment]
@stabenfeldt great to hear, and glad you got it ironed out!
