### ISSUE TITLE
Gemspec does not allow factory_girl 4.6 or 4.7

### ISSUE THREAD

**Issue by aselder** [thoughtbot/factory_girl_rails#203]
The gemspec locks to ~> 4.5.0, meaning we can't use 4.6 or 4.7.

Is this intentional (does factory_girl 4.6 break something) or is just waiting for a PR to change it?

If it's the latter, I'll be happy to whip it up.

**Comment by joshuaclayton** [comment]
I've just shipped [4.7.0](https://github.com/thoughtbot/factory_girl_rails/releases/tag/v4.7.0); apologies for the delay!

**Comment by aselder** [comment]
@joshuaclayton You da man! Thanks!
