### ISSUE TITLE
Rails 5 loading and validation issues

### ISSUE THREAD

**Issue by maxbeizer** [thoughtbot/factory_girl_rails#218]
I started a new Rails 5 project today and ran into a series weird issues with FGR.

[Example app to reproduce issues](https://github.com/maxbeizer/factory_girl_rspec)
rails 5.0.0.1
factory_girls_rails 4.7.0
rspec-rails 3.5.2
shoulda-matchers 3.1.1

For more context, on the example app:
Model: `User`
Attributes: `email:string:uniq, admin:boolean`

## Not registering factories properly
I generated a simple [user_factory](https://github.com/maxbeizer/factory_girl_rspec/blob/master/spec/factories/users.rb) and sequenced email generation. In trying to use Syntax Methods as referenced in the [getting started guide](http://www.rubydoc.info/gems/factory_girl/file/GETTING_STARTED.md). I get the following error:

```
uninitialized constant FactoryGirl (NameError)
```

So I added a require statement to `/spec/support/factory_girl.rb`:
```ruby
require 'factory_girl'

RSpec.configure do |config|
  config.include FactoryGirl::Syntax::Methods
end
```

Add the require statement leads to the following error:
```
ArgumentError Factory not registered: user
```

yet there clearly is a `/spec/factories/users.rb`

## Adding definitions hack
I read a number of issue reports on FGR, factory_girl, and StackOverflow and decided to try this ([changes viewable on this PR](https://github.com/maxbeizer/factory_girl_rspec/pull/1)):

```ruby
require 'factory_girl'

RSpec.configure do |config|
  config.include FactoryGirl::Syntax::Methods

  config.before(:all) do
    FactoryGirl.find_definitions if FactoryGirl.factories.count == 0 # I also tried FactoryGirl.reload here
  end
end
```

Running that, I get:
```
ActiveRecord::RecordInvalid: Validation failed: Admin can't be blank
```

Introspecting the object in the test: it has the attribute `admin` set to false yet the spec fails saying the value is blank. :scream:

Am I doing it wrong?

Apologies if these are should be seperate issues, but they seem related. If I have missed anything on the setup to reproduce this, then I apologize for the noise. And thanks for the awesome OSS.

**Comment by joshuaclayton** [comment]
@maxbeizer the first thing I noticed is that the Gemfile group for FGR isn't set for `:test`; that's the first place I'd start. Under normal conditions you shouldn't have to require anything from FG for it to work if the Gemfile is correct. Please let me know where that gets you!

**Comment by maxbeizer** [comment]
@joshuaclayton I updated my example repo to move FGR to development and test :facepalm:. That's just a mistake from copy stuff over into an example app. In any event, with the gem in test and development groups, I still see: 
```
Validation failed: Admin can't be blank
```

If I remove the require statement, I get the uninitialized constant error as reported above.

Thanks for looking into this with me 😄

**Comment by joshuaclayton** [comment]
@maxbeizer if you attempt to create a record from a Rails console, e.g. `User.create!(admin: false, email: "brand-new@example.com")`, what happens?

**Comment by maxbeizer** [comment]
```
User.create!(admin: false, email: "brand-new@example.com")
   (0.1ms)  begin transaction
  User Exists (0.4ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = ? LIMIT ?  [["email", "brand-new@example.com"], ["LIMIT", 1]]
   (0.0ms)  rollback transaction
ActiveRecord::RecordInvalid: Validation failed: Admin can't be blank
```

**Comment by maxbeizer** [comment]
Yep. Can't validate presence on a boolean field. Example updated. I still have to require factory girl for some reason.

**Comment by maxbeizer** [comment]
Digging into this more, I have not found anything new. So for the time being I will be requiring factory girl in my support file. If I figure out where I went wrong or learn something new, I'll reopen. Thanks for looking into this with me @joshuaclayton and thanks for all the OSS work you do .
