### ISSUE TITLE
FactoryGirlRails stopped working - build works, but create doesn't.

### ISSUE THREAD

**Issue by pawdro** [thoughtbot/factory_girl_rails#230]
After updating ruby `2.3.0 -> 2.4.0` factory_girl_rails stopped working (I cannot save any element to db). I have a problem that `build` works, but `create` returns error:
```
Failure/Error: let(:education)           { create(:education) }

NoMethodError:
  undefined method `<<' for {:read_timeout=>60, :continue_timeout=>nil, :debug_output=>nil}:Hash
Did you mean?  <
from /Users/me/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/protocol.rb:219:in `writing'
```

AFAIK the problem lies in saving objects to db. Whenever I try to save some object, like user (`user.save`), I receive the same error.
But saving elements using `rails console` works ok

I run:
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
Rails 5.0.1
factory_girl 4.8.0
factory_girl_rails 4.8.0
rspec (3.5.0)

-------------
upgrade to the latest version of `webmock` solved the issue.

**Comment by francois-tilkee** [comment]
Same here but upgrading `webmock` didn't solve the issue for me

**Comment by pjar** [comment]
We have same error but we don't even use `webmock`.
